// <auto-generated />
using System;
using Fit4TheFloor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fit4TheFloor.Migrations.BlogPostDb
{
    [DbContext(typeof(BlogPostDbContext))]
    [Migration("20190514195046_FitPostsLocal-initial")]
    partial class FitPostsLocalinitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fit4TheFloor.Models.BlogPost", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Category");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Discussion");

                    b.Property<string>("Images");

                    b.Property<string>("Videos");

                    b.HasKey("ID");

                    b.ToTable("BlogPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
