// <auto-generated />
using System;
using Fit4TheFloor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fit4TheFloor.Migrations.SalesDb
{
    [DbContext(typeof(SalesDbContext))]
    partial class SalesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fit4TheFloor.Models.Cart", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BuyerEmail");

                    b.Property<DateTime?>("Closed");

                    b.Property<decimal>("OrderTotal");

                    b.Property<string>("PayPalConf");

                    b.Property<string>("ShipAddress");

                    b.Property<decimal>("ShippingFee");

                    b.HasKey("ID");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Fit4TheFloor.Models.Print", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Description");

                    b.Property<string>("ImageURL");

                    b.HasKey("ID");

                    b.ToTable("Prints");
                });

            modelBuilder.Entity("Fit4TheFloor.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Colors");

                    b.Property<string>("Description");

                    b.Property<string>("ImageURL");

                    b.Property<decimal>("Price");

                    b.Property<string>("Sizes");

                    b.HasKey("ID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Fit4TheFloor.Models.Purchase", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CartID");

                    b.Property<DateTime?>("Closed");

                    b.Property<int>("Color");

                    b.Property<decimal>("ExtPrice");

                    b.Property<int>("PrintColor");

                    b.Property<int>("PrintID");

                    b.Property<int>("ProductID");

                    b.Property<int>("Qty");

                    b.Property<int>("Size");

                    b.HasKey("ID");

                    b.HasIndex("CartID");

                    b.HasIndex("PrintID");

                    b.HasIndex("ProductID");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("Fit4TheFloor.Models.Purchase", b =>
                {
                    b.HasOne("Fit4TheFloor.Models.Cart", "Cart")
                        .WithMany("Purchases")
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fit4TheFloor.Models.Print", "Print")
                        .WithMany()
                        .HasForeignKey("PrintID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fit4TheFloor.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
