// <auto-generated />
using System;
using Fit4TheFloor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fit4TheFloor.Migrations.StatsDb
{
    [DbContext(typeof(StatsDbContext))]
    [Migration("20190514202502_FitStatsLocal-initial")]
    partial class FitStatsLocalinitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fit4TheFloor.Models.ClientMessage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contents");

                    b.Property<string>("From");

                    b.Property<DateTime?>("Read");

                    b.Property<DateTime>("Sent");

                    b.Property<string>("To");

                    b.HasKey("ID");

                    b.ToTable("ClientMessages");
                });

            modelBuilder.Entity("Fit4TheFloor.Models.WeighIn", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Chest");

                    b.Property<DateTime>("Date");

                    b.Property<int>("HeartRate");

                    b.Property<int>("Height");

                    b.Property<int>("Hips");

                    b.Property<string>("UserEmail");

                    b.Property<int>("Waist");

                    b.Property<int>("Weight");

                    b.HasKey("ID");

                    b.ToTable("WeighIns");
                });
#pragma warning restore 612, 618
        }
    }
}
